In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
type(np)

module

In [3]:
lst = [4, 6, 7]

In [4]:
type(lst[0])

int

In [5]:
myNewList = [str(i) for i in lst]

In [6]:
myNewList

['4', '6', '7']

In [7]:
type(myNewList[0])

str

In [8]:
# np?

In [9]:
lst1 = [4, 5, 7, 10]

In [10]:
np_arr1 = np.array(lst1)

In [11]:
np_arr1

array([ 4,  5,  7, 10])

In [12]:
np_arr2 = np.array([3, 5, 10])

In [13]:
np_arr2.ndim

1

In [14]:
np_arr2.size

3

In [15]:
np_arr2.dtype

dtype('int32')

In [18]:
np_arr3 = np.array([3, 5, 10], dtype="int64")

In [22]:
np_arr4 = np.array([3, 5, 10], dtype=np.float32)

In [23]:
np_arr4.dtype

dtype('float32')

In [24]:
np_arr4

array([ 3.,  5., 10.], dtype=float32)

In [25]:
np_arr5 = np.array([3, 5, 10], dtype=np.complex)

In [26]:
np_arr5

array([ 3.+0.j,  5.+0.j, 10.+0.j])

In [35]:
np_arr5 = np.array([3, 5, 65535], dtype=np.uint16)

In [36]:
np_arr5

array([    3,     5, 65535], dtype=uint16)

In [37]:
np_arr6 = np.array([[2, 6, 7], [2, 7, 10]])

In [45]:
np_arr6

array([[ 2,  6,  7],
       [ 2,  7, 10]])

In [46]:
value = np_arr6.reshape(3, 2)

In [47]:
value

array([[ 2,  6],
       [ 7,  2],
       [ 7, 10]])

In [40]:
np_arr6 > 5

array([[False,  True,  True],
       [False,  True,  True]])

In [42]:
a = [np_arr6 > 5]

In [43]:
a

[array([[False,  True,  True],
        [False,  True,  True]])]

In [50]:
np_arr7 = np.arange(0, 100).reshape(10, 10)

In [51]:
np_arr7

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
np_arr7[1,6] = 100

In [55]:
np_arr7[1:3]

array([[ 10,  11,  12,  13,  14,  15, 100,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [56]:
np_arr7[ : , 7 : ]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29],
       [37, 38, 39],
       [47, 48, 49],
       [57, 58, 59],
       [67, 68, 69],
       [77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])

In [59]:
# np_arr7[::-1]

In [62]:
np_arr8 = np.random.randint(0, 100, (10, 10))

In [64]:
# np_arr8

In [71]:
np_arr9 = np.zeros((10, 10), dtype=np.int32)

In [74]:
np_arr9 + 10

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [75]:
np_arr10 = np.full((5, 5), 4)

In [76]:
np_arr10

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [78]:
np_arr11 = np.eye(5)

In [79]:
np_arr11

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
np_arr12 = np.arange(1, 11)

In [82]:
np_arr12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
np_arr12 * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [84]:
np_arr12 > 10

array([False, False, False, False, False, False, False, False, False,
       False])

In [85]:
np_arr12.sum()

55

In [86]:
np_arr12.mean()

5.5

In [87]:
np_arr12.std()

2.8722813232690143

In [89]:
np.log(np_arr12)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [90]:
def imaginaryString():
    
    arr_1 = ['Q', 'Y', 'A', 'P', 'V', 'F', 'C', 'J', 'B', 'E']
    arr_2 = ['V', 'Q', 'Y', 'J', 'W', 'A', 'G', 'N', 'U', 'S']

    arr_3 = np.intersect1d(arr_1, arr_2)
    arr_3 = np.sort(arr_3)

    a = [4, 2, 1, 3, 0]
    i = 0

    while i < len(arr_3):
        print(arr_3[ a[i] ])
        i = i + 1

In [91]:
imaginaryString()

Y
Q
J
V
A
